# Generated by Django 3.2.14 on 2022-07-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_art',
            name='price',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=6),
        ),
    ]
